test: &TEST
  cargo_cache:
    folder: $CARGO_HOME/registry
  build_script:
    - . $HOME/.cargo/env || true
    - cargo build --all --all-targets
  test_script:
    - . $HOME/.cargo/env || true
    - cargo test --all
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  matrix:
    - name: FreeBSD 14
      freebsd_instance:
        image: freebsd-14-0-release-amd64-ufs
    - name: FreeBSD 13
      freebsd_instance:
        image: freebsd-13-2-release-amd64
  install_script: |
    fetch https://sh.rustup.rs -o rustup.sh
    sh rustup.sh -y --profile=minimal
  << : *TEST

task:
  name: OSX/arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  << : *TEST

task:
  name: Linux
  container:
    image: rust:latest
  << : *TEST
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version

test_task:
  name: nightly
  depends_on:
    - FreeBSD 14
    - FreeBSD 13
    - OSX/arm64
    - Linux
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
  build_script: cargo build --all
  test_script: cargo test --all
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
  minver_test_script:
    - cargo update -Zdirect-minimal-versions
    - cargo check --all-targets
  before_cache_script: rm -rf $CARGO_HOME/registry/index
